version: '3.8'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: messecure-synapse
    depends_on:
      - postgres
    volumes:
      - ./synapse/homeserver.yaml:/data/homeserver.yaml
      - ./synapse/data:/data
    environment:
      - SYNAPSE_SERVER_NAME=localhost
      - SYNAPSE_REPORT_STATS=yes
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
    ports:
      - "8008:8008"
    restart: unless-stopped

  postgres:
    image: docker.io/postgres:14-alpine
    container_name: messecure-db
    environment:
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=aComplexPassphraseNobodyCanGuess
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  messecure:
    build:
      context: .
      dockerfile: Dockerfile
      target: production  # ou 'production' selon vos besoins
    container_name: messecure-app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - synapse
    environment:
      - NODE_ENV=development
    restart: unless-stopped

# At the end of your docker-compose.yml
volumes:
  postgres_data:
