version: '3.8'

services:
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: messecure-synapse
    depends_on:
      - postgres
    volumes:
      - ./synapse/homeserver.yaml:/data/homeserver.yaml
      - ./synapse/data:/data
    environment:
      SYNAPSE_SERVER_NAME: localhost  # Replace with your actual domain
      SYNAPSE_REPORT_STATS: 'yes'
      SYNAPSE_CONFIG_PATH: /data/homeserver.yaml
    ports:
      - "8008:8008"
    restart: unless-stopped

  postgres:
    image: postgres:14-alpine
    container_name: messecure-db
    environment:
      POSTGRES_USER: synapse
      POSTGRES_PASSWORD: aComplexPassphraseNobodyCanGuess  # Consider using Docker secrets for sensitive data
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  messecure:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner  # Specifies the final stage in the Dockerfile
    container_name: messecure-app
    ports:
      - "3000:3000"
    depends_on:
      - synapse
      - postgres
    environment:
      NODE_ENV: production
      # Add other environment variables as needed, e.g.,
      # DATABASE_URL: postgres://synapse:aComplexPassphraseNobodyCanGuess@postgres:5432/synapse
      # SYNAPSE_URL: http://synapse:8008
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
